name: core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0
  meta: ^1.1.8
  logging: ^0.11.4
  utilities:
    path: ../utilities
  fractional:
    path: ../fractional
  sentry: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.9.4