name: rive_api
description: Rive backend API
version: 1.0.0
author:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.1
  http: ^0.12.0
  encrypt: ^4.0.0
  logging: ^0.11.4
  utilities:
    path: ../utilities
  local_data:
      path: ../local_data
  window_utils:
      path: ../window_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.14.2
  meta: ^1.1.8

flutter: