name: rive_editor
description: The Rive editor written in Flutter.
version: 0.0.37

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  rive_core:
    path: ../rive_core
  tree_widget:
    path: ../tree_widget
  cursor:
    path: ../cursor
  window_utils:
    path: ../window_utils
  rive_api:
    path: ../rive_api
  rive_widgets:
    path: ../rive_widgets
  utilities:
    path: ../utilities

  http: ^0.12.0+4
  trotter: ^1.1.1
  path_drawing: ^0.4.1
  dotted_border: ^1.0.5
  flutter_widgets: ^0.1.12
  url_launcher: ^5.4.2
  rxdart: ^0.24.0

  path_provider: ^1.6.5
  path_provider_macos: ^0.0.4

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 888f58887b388f5e875662e1def33f2d12696564

dev_dependencies:
  test: any
  mockito: ^4.1.1
  image_res: ^0.2.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/icons/

  uses-material-design: true
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
