name: rive_editor
description: The Rive editor written in Flutter.
version: 0.4.18

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  rive_core:
    path: ../rive_core
  tree_widget:
    path: ../tree_widget
  cursor:
    path: ../cursor
  window_utils:
    path: ../window_utils/window_utils
  # Need to include this as endorsed web plugins not supported yet
  window_utils_web:
    path: ../window_utils/window_utils_web
  rive_api:
    path: ../rive_api
  rive_widgets:
    path: ../rive_widgets
  utilities:
    path: ../utilities
  rive: 
    path: ../../submodules/rive-flutter/

  http: ^0.12.2
  dotted_border: ^1.0.6
  flutter_widgets: ^0.1.12
  url_launcher: ^5.7.7
  rxdart: ^0.24.1
  collection: ^1.14.13
  cached_network_image:
    git: 
      url: git://github.com/luigi-rosso/flutter_cached_network_image.git
      ref: fix_flutter_60239

  path_provider: ^1.6.21
  path_provider_macos: ^0.0.4+4
  bezier: ^1.1.5
  
  logging: ^0.11.4

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      # ref: 888f58887b388f5e875662e1def33f2d12696564
      
  hashids2: ^1.0.3
  slugify2: ^0.2.1
  flutter_markdown: ^0.5.0

dev_dependencies:
  test: any
  mockito: ^4.1.3
  image_res: ^0.2.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/icon_atlases/
    - assets/web/
    - assets/animations/

  uses-material-design: true
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
