name: Tests

on:
    # pull_request:
    push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Install Flutter and Dart
      - name: Checkout and install flutter and dart
        run: |
          git clone https://github.com/flutter/flutter.git
          
      - name: Add the flutter commmand path
        #run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin"
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Add the dart command path
        #run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin"
        run: echo "$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Setup flutter
        run: |
          flutter channel dev
          flutter doctor

      # Run the utilities tests
      - name: Install utilities dependencies
        run: cd packages/utilities && pub get
      - name: Run utilities tests
        run: cd packages/utilities && pub run test

      # Run the editor tests
      - name: Install editor dependencies
        run: cd packages/editor && flutter pub get
      - name: Run editor tests
        run: cd packages/editor && flutter test
    
      # Run the co-op server tests
      - name: Install coop server dependencies
        run: cd packages/coop_server && pub get
      - name: Run coop server tests
        run: cd packages/coop_server && pub run test

        # Run the core tests
      - name: Install core dependencies
        run: cd packages/core && pub get
      - name: Run core tests
        run: cd packages/core && pub run test

        # Run the fractional tests
      - name: Install fractional dependencies
        run: cd packages/fractional && pub get
      - name: Run fractional tests
        run: cd packages/fractional && pub run test

        # Run the tree widget tests
      - name: Install tree widget dependencies
        run: cd packages/tree_widget && flutter pub get
      - name: Run tree widget tests
        run: cd packages/tree_widget && flutter test

        # Run the rive core tests
      - name: Install rive core dependencies
        run: cd packages/rive_core && flutter pub get
      - name: Run rive core tests
        run: cd packages/rive_core && flutter test
